title: Aathish's Archive
description: "Aathish's Thoughts, Projects and Ideas"
author:
  name: "Aathish Sivasubrahmanian"
  email: "aathish04@gmail.com"
  url: "https://aathish04.github.io/"

include:
  - _pages

baseurl: ""

exclude: ["compose.yaml","Gemfile","Gemfile.lock"]

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Aathish Sivasubrahmanian"
year : "2023"
google_analytics: "G-XLJRH34LK6"